### ISSUE TITLE
Actively being developed?

### ISSUE THREAD

**Issue by idibidiart** [ericelliott/rfx#21]
?

**Comment by ericelliott** [comment]
rtype is under active devolpement. What rfx needs next is an rtype parser than can turn rtype signatures into predicate functions for runtime type checking. Would you like to help with that?

**Comment by idibidiart** [comment]
This is what Flow is missing! :) The couple attempts I looked at for combining Flow with runtime checks, one by my colleague @codemix https://github.com/codemix/babel-plugin-typecheck and a more powerful one by @gcanti https://github.com/gcanti/babel-plugin-tcomb are not doing what you're suggesting with use of predicate functions. 

I'm looking at this https://flowtype.org/docs/dynamic-type-tests.html to better understand what's possible with Flow and how it compares to rtype/rfx but I have a feeling that your thinking is ahead of Flow's in this respect.

Problem is I've just started considering the use of tools like rtype/rfx and Flow/tcomb for static+runtime checks and I'm trying to decide if I only want just typed interfaces or also typed implementations. Not sure what the latter would buy me. But at any rate, my understanding of the nitty gritty details is not there yet and will take me a while to ramp up. Else, I'd jump on the opportunity to help!  

I'll spread the word and I hope others will bite!

:)

**Comment by gcanti** [comment]
Hi @idibidiart

> are not doing what you're suggesting with use of predicate functions

could you please share more details?

**Comment by idibidiart** [comment]
hi @gcanti 

My understanding (from perusing the Readme for your plugin) is that you're using the tcomb library to implement runtime type checking, while leveraging Flow and your own routines to create runtime type checks from Flow annotations. 

If that's correct, then rtype and rfx differ in that the runtime type checks could be generated automatically with the same type checking logic functions that are used during static analysis (the said predicate functions). I think absolute equality between static and runtime checks requires that.

I'm just getting into this so I'm eager to be corrected if I'm wrong.

**Comment by gcanti** [comment]
> with the same type checking logic functions that are used during static analysis

Maybe I'm missing something, I don't see any static type checker here nor in the rtype repo. @ericelliott is there something in the work? I'd be very interested.

> I think absolute equality between static and runtime checks requires that

I agree. Please note that tcomb and Flow semantics are very close.

**Comment by ericelliott** [comment]
There is a [static type checker](https://github.com/ericelliott/rtype/issues/89) in the works. However, the runtime checks have nothing to do with that. As I mentioned above, the plan for runtime is to read the rtype signature and compile it to a set of predicate functions which will wrap the actual function call at runtime. Type checking can be easily flipped on or off, which will have the effect of exposing either the wrapped function (on) or the raw function (off) from the interface.

IMO, the big differentiating feature of rfx is that it gives you a rich self-documenting interface for runtime reflection which is not supplied by tools like Flow. Doing so allows you to build rich runtime developer tools which are not possible otherwise.

**Comment by idibidiart** [comment]
What is an "rtype signature" ?

**Comment by ericelliott** [comment]
See [reading function signatures](https://github.com/ericelliott/rtype#reading-function-signatures).
